name: hello-world
on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v4
      - run: echo "$(hello_world.txt)"      
